# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-database.c95hdur4jh4f.us-east-2.rds.amazonaws.com:3306/realmeetaws?&serverTimezone=UTC&useSSL=false
    username: admin

