# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.c95hdur4jh4f.us-east-2.rds.amazonaws.com:3306/realmeet-db?&serverTimezone=UTC&useSSL=false
    username: admin

